/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3d10e9a3-b48c-4cf2-a411-5a41ab03e046",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Ik3eF3PMj",
    "aws_user_pools_web_client_id": "1ctl1vgogf4i0vq1s9f4v7l0nr",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://khzzrl2onzhvnnhuta27lkxjj4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rxkftiot5bhnxfpcpcgavuo7se"
};


export default awsmobile;
