/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://6hzuf5v7vba2xgczs3fqf7okje.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7tfmwv2p25a27ceo6hg6lxhuim",
    "aws_cognito_identity_pool_id": "us-east-1:51bd3dea-05b1-4a07-9172-a786845603c4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_X7L4aojpb",
    "aws_user_pools_web_client_id": "3n22mr9rfc08498mdfqfrf1ada",
    "oauth": {}
};


export default awsmobile;
