/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://n4drzocuu5aldehy4zzh5fnhby.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-xlpvhwafhjcubagjmxg5zsnozu",
    "aws_cognito_identity_pool_id": "us-east-1:3d10e9a3-b48c-4cf2-a411-5a41ab03e046",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_0iP3Btter",
    "aws_user_pools_web_client_id": "co5c5o332g1u2h68tol2nojdt",
    "oauth": {}
};


export default awsmobile;
